[theme]
primaryColor="#1d90c1"
backgroundColor="#070d34"
secondaryBackgroundColor="#101a46"
textColor="#ffffff"


dkey = "c0bp6nt0_wQf6VD9qgSYSTrALwR19W3xwog7ZHaxx"

dkey2 = "c0bp6nt0_adeL6WY22Dut67TdnvGBYTrF2fyL9krQ"
