[theme]
primaryColor="#1d90c1"
backgroundColor="#070d34"
secondaryBackgroundColor="#101a46"
textColor="#ffffff"

[server]
enableCORS = false
enableWebsocketCompression = false

[browser]
serverAddress = 35.230.127.150
