[theme]
primaryColor="#1d90c1"
backgroundColor="#070d34"
secondaryBackgroundColor="#101a46"
textColor="#ffffff"


DETA_KEY = "c0bp6nt0_wQf6VD9qgSYSTrALwR19W3xwog7ZHaxx"

DETA_KEY2 = "c0bp6nt0_adeL6WY22Dut67TdnvGBYTrF2fyL9krQ"
